Step5
Kouch-Sato/NextToDo pull request #1
Opened 2017-11-24 10:43 UTC by Kouch-Sato

11/24(金)
タスクの一覧表示、statusで場合分け、編集フォームを作りました。
ユーザー関係、ソートはまだ実装していません。

2017-11-24 12:12 UTC, siso9to requested changes
ざっとレビューしました。あまり直接的な正解は書かないようにしたつもり。
enum使うと挙動でハマるところがあるかもしれないけど、一旦自分で調べて対応してみてください

2017-11-24 12:12 UTC, siso9to commented on app/controllers/tasks_controller.rb
> +    @tasks3 = Task.all.where(status: 3)
- 変数名を分かりやすいものにしましょう
- enumを使いましょう

2017-11-24 12:12 UTC, siso9to commented on app/controllers/tasks_controller.rb
> +    @task.label = "blue"
毎回Controllerでnewするたびにデフォルト値をセットする必要があるのは手間なので、Model側で工夫しましょう

2017-11-24 12:12 UTC, siso9to commented on app/controllers/tasks_controller.rb
> +    @task.status = 1
statusはDBのデフォルト値が0だと思うので、未着手の時の値を0にするとデフォルト値を手動で設定する必要がないです。

2017-11-24 12:12 UTC, siso9to commented on app/views/tasks/edit.html.erb
> +        <%= f.select :status, [["未着手", 1], ["実行中", 2], ["完了済み", 3]], :class => "form-control"  %>
べた書きしないように（i18nのステップで）直しましょう

2017-11-24 12:12 UTC, siso9to commented on app/views/tasks/edit.html.erb
> +        <%= f.label :label_blue, "blue", :class => "label label-blue" %>
ラベルもベタ書きせずに済むようにしましょう

2017-11-24 12:12 UTC, siso9to commented on app/views/tasks/index.html.erb
> +    <li><a href="#table3" data-toggle="tab">完了済み<span class-"tasks-count"><%= @tasks3.count %></span></a></li>
細かいところだけどActiveRecordはcountよりsizeを使った方が早い場合があります
※countは毎回DBを読むけどsizeはクエリをload済みの場合はDBを読まないため

2017-11-27 07:00 UTC, Kouch-Sato commented on app/views/tasks/index.html.erb
> +    <li><a href="#table3" data-toggle="tab">完了済み<span class-"tasks-count"><%= @tasks3.count %></span></a></li>
改善しました。

2017-11-27 07:01 UTC, Kouch-Sato commented on app/controllers/tasks_controller.rb
> +    @tasks3 = Task.all.where(status: 3)
改善しました。

2017-11-27 07:01 UTC, Kouch-Sato commented on app/controllers/tasks_controller.rb
> +    @task.label = "blue"
migrationファイルを作りdefaultでblueを入れるようにしました。

2017-11-27 07:02 UTC, Kouch-Sato commented on app/controllers/tasks_controller.rb
> +    @task.status = 1
statusは、開かれているタブに応じて初期値を設定しようと思っているのでとりあえず後回しにしました。

2017-12-04 05:44 UTC, siso9to requested changes
usersテーブルのmigrationファイルが無いので、漏れてるのであれば git add してください！

2017-12-04 05:44 UTC, siso9to commented on app/controllers/tasks_controller.rb
> +    if params[:label].present?
先にこのチェックをした方が無駄が無いのでは。
elseを書いて、その中で 5〜7行目の処理を書いた方が良さそう。

2017-12-04 05:44 UTC, siso9to commented on app/controllers/tasks_controller.rb
> +    @yet_tasks = @current_user.tasks.all.yet
`@current_user.tasks.all.yet`　などの
.all は不要では。

2017-12-04 08:35 UTC, Kouch-Sato commented
#5 #14

2017-12-05 09:07 UTC, siso9to approved these changes
OKです。
public/uploads/tmp 以下はgitに登録する必要無いと思うので、.gitignoreに登録するなりしてアップロードした画像がgitに保存されないようにしましょう。

もうマージしてしまって大丈夫です。

2017-12-05 09:38 UTC, Kouch-Sato commented
ありがとうございます！マージします！

2017-12-06 04:53 UTC, merged